name: Build & Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-configuration-cache

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: enderbackpacks-mod-${{ github.sha }}
        path: build/libs/*.jar
        if-no-files-found: error
        retention-days: 30

    - name: Upload build reports on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports-${{ github.sha }}
        path: build/reports/
        retention-days: 7
